/**
 * Marea - Base de datos completa de los 83 spots de surf en España
 * Cada spot incluye enlace directo a la webapp: https://marea.onrender.com/#/spot/:id
 */
window.MAREA_SPOTS = [
  {
    id: "patos",
    name: "Patos",
    region: "Pontevedra",
    zone: "galicia",
    facing: 270,
    facingCardinal: "O",
    tidePref: "Media marea",
    lat: 42.158,
    lon: -8.824,
    url: "https://marea.onrender.com/#/spot/patos",
    score: 2.4,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,2 m",
    wavePeriod: "8 s",
    waveDir: "NO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,1 m",
    port: "Baiona",
    webcam: null,
  },
  {
    id: "lanzada",
    name: "A Lanzada",
    region: "Pontevedra",
    zone: "galicia",
    facing: 260,
    facingCardinal: "O",
    tidePref: "Todas las mareas",
    lat: 42.447,
    lon: -8.88,
    url: "https://marea.onrender.com/#/spot/lanzada",
    score: 3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "1,0 m",
    wavePeriod: "8 s",
    waveDir: "NO",
    windSpeed: "13 kn",
    windLabel: "Terral",
    windTag: "tag-terral",
    tideState: "Bajando 2,1 m",
    port: "Sanxenxo (Ría de Pontevedra)",
    webcam: null,
  },
  {
    id: "montalvo",
    name: "Montalvo",
    region: "Pontevedra",
    zone: "galicia",
    facing: 200,
    facingCardinal: "SSO",
    tidePref: "Media marea",
    lat: 42.398,
    lon: -8.849,
    url: "https://marea.onrender.com/#/spot/montalvo",
    score: 1.5,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,0 m",
    wavePeriod: "8 s",
    waveDir: "NO",
    windSpeed: "13 kn",
    windLabel: "Terral",
    windTag: "tag-terral",
    tideState: "Bajando 2,1 m",
    port: "Sanxenxo (Ría de Pontevedra)",
    webcam: null,
  },
  {
    id: "barra",
    name: "Barra",
    region: "Pontevedra",
    zone: "galicia",
    facing: 260,
    facingCardinal: "O",
    tidePref: "Media marea",
    lat: 42.261,
    lon: -8.852,
    url: "https://marea.onrender.com/#/spot/barra",
    score: 2.5,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,2 m",
    wavePeriod: "8 s",
    waveDir: "NO",
    windSpeed: "8 kn",
    windLabel: "Terral",
    windTag: "tag-terral",
    tideState: "Bajando 2,3 m",
    port: "Vigo",
    webcam: null,
  },
  {
    id: "razo",
    name: "Razo",
    region: "A Coruña",
    zone: "galicia",
    facing: 315,
    facingCardinal: "NO",
    tidePref: "Todas las mareas",
    lat: 43.294,
    lon: -8.702,
    url: "https://marea.onrender.com/#/spot/razo",
    score: 1.8,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,5 m",
    wavePeriod: "8 s",
    waveDir: "N",
    windSpeed: "9 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,3 m",
    port: "Malpica",
    webcam: null,
  },
  {
    id: "doninos",
    name: "Doniños",
    region: "A Coruña",
    zone: "galicia",
    facing: 280,
    facingCardinal: "O",
    tidePref: "Todas las mareas",
    lat: 43.495,
    lon: -8.32,
    url: "https://marea.onrender.com/#/spot/doninos",
    score: 2.3,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,6 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "11 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,6 m",
    port: "Ferrol",
    webcam: null,
  },
  {
    id: "pantin",
    name: "Pantín",
    region: "A Coruña",
    zone: "galicia",
    facing: 315,
    facingCardinal: "NO",
    tidePref: "Media marea",
    lat: 43.639,
    lon: -8.114,
    url: "https://marea.onrender.com/#/spot/pantin",
    score: 2.7,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,8 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "9 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,5 m",
    port: "Cedeira",
    webcam: null,
  },
  {
    id: "frouxeira",
    name: "A Frouxeira",
    region: "A Coruña",
    zone: "galicia",
    facing: 315,
    facingCardinal: "NO",
    tidePref: "Media marea",
    lat: 43.612,
    lon: -8.167,
    url: "https://marea.onrender.com/#/spot/frouxeira",
    score: 2.5,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,6 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "10 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,5 m",
    port: "Cedeira",
    webcam: null,
  },
  {
    id: "orzan",
    name: "Orzán",
    region: "A Coruña",
    zone: "galicia",
    facing: 300,
    facingCardinal: "ONO",
    tidePref: "Media marea",
    lat: 43.372,
    lon: -8.408,
    url: "https://marea.onrender.com/#/spot/orzan",
    score: 1.3,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,2 m",
    wavePeriod: "6 s",
    waveDir: "N",
    windSpeed: "8 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,6 m",
    port: "A Coruña",
    webcam: null,
  },
  {
    id: "bastiagueiro",
    name: "Bastiagueiro",
    region: "A Coruña",
    zone: "galicia",
    facing: 330,
    facingCardinal: "NNO",
    tidePref: "Media marea",
    lat: 43.343,
    lon: -8.364,
    url: "https://marea.onrender.com/#/spot/bastiagueiro",
    score: 1.6,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,2 m",
    wavePeriod: "6 s",
    waveDir: "N",
    windSpeed: "8 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 2,6 m",
    port: "A Coruña",
    webcam: null,
  },
  {
    id: "caion",
    name: "Caión",
    region: "A Coruña",
    zone: "galicia",
    facing: 340,
    facingCardinal: "NNO",
    tidePref: "Media marea",
    lat: 43.316,
    lon: -8.61,
    url: "https://marea.onrender.com/#/spot/caion",
    score: 1.6,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,4 m",
    wavePeriod: "6 s",
    waveDir: "N",
    windSpeed: "8 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 2,6 m",
    port: "Langosteira (Puerto exterior de A Coruña)",
    webcam: null,
  },
  {
    id: "nemina",
    name: "Nemiña",
    region: "A Coruña",
    zone: "galicia",
    facing: 270,
    facingCardinal: "O",
    tidePref: "Media marea",
    lat: 43.007,
    lon: -9.261,
    url: "https://marea.onrender.com/#/spot/nemina",
    score: 2.2,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,8 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "13 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,0 m",
    port: "Fisterra",
    webcam: null,
  },
  {
    id: "carnota",
    name: "Carnota",
    region: "A Coruña",
    zone: "galicia",
    facing: 260,
    facingCardinal: "O",
    tidePref: "Todas las mareas",
    lat: 42.825,
    lon: -9.108,
    url: "https://marea.onrender.com/#/spot/carnota",
    score: 3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "1,3 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "11 kn",
    windLabel: "Terral",
    windTag: "tag-terral",
    tideState: "Bajando 2,4 m",
    port: "Portosín (Ría de Muros y Noia)",
    webcam: null,
  },
  {
    id: "sanxurxo",
    name: "San Xurxo",
    region: "A Coruña",
    zone: "galicia",
    facing: 290,
    facingCardinal: "ONO",
    tidePref: "Media marea",
    lat: 43.528,
    lon: -8.303,
    url: "https://marea.onrender.com/#/spot/sanxurxo",
    score: 2.4,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "11 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,6 m",
    port: "Ferrol",
    webcam: null,
  },
  {
    id: "ponzos",
    name: "Ponzos",
    region: "A Coruña",
    zone: "galicia",
    facing: 300,
    facingCardinal: "ONO",
    tidePref: "Media marea",
    lat: 43.557,
    lon: -8.266,
    url: "https://marea.onrender.com/#/spot/ponzos",
    score: 2.4,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,7 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "10 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,6 m",
    port: "Ferrol",
    webcam: null,
  },
  {
    id: "tapia",
    name: "Tapia",
    region: "Asturias",
    zone: "asturias",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.568,
    lon: -6.948,
    url: "https://marea.onrender.com/#/spot/tapia",
    score: 2.4,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "5 s",
    waveDir: "NNE",
    windSpeed: "1 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,7 m",
    port: "Tapia",
    webcam: null,
  },
  {
    id: "xago",
    name: "Xagó",
    region: "Asturias",
    zone: "asturias",
    facing: 320,
    facingCardinal: "NO",
    tidePref: "Media marea",
    lat: 43.604,
    lon: -5.921,
    url: "https://marea.onrender.com/#/spot/xago",
    score: 3.2,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "7 s",
    waveDir: "NNO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Avilés (San Juan de Nieva)",
    webcam: null,
  },
  {
    id: "salinas",
    name: "Salinas",
    region: "Asturias",
    zone: "asturias",
    facing: 340,
    facingCardinal: "NNO",
    tidePref: "Media marea",
    lat: 43.584,
    lon: -5.954,
    url: "https://marea.onrender.com/#/spot/salinas",
    score: 3.2,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "7 s",
    waveDir: "NNO",
    windSpeed: "5 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Avilés (San Juan de Nieva)",
    webcam: null,
  },
  {
    id: "rodiles",
    name: "Rodiles",
    region: "Asturias",
    zone: "asturias",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.534,
    lon: -5.38,
    url: "https://marea.onrender.com/#/spot/rodiles",
    score: 3.3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "6 s",
    waveDir: "NNO",
    windSpeed: "9 kn",
    windLabel: "Terral",
    windTag: "tag-terral",
    tideState: "Bajando 2,8 m",
    port: "Gijón",
    webcam: null,
  },
  {
    id: "penarronda",
    name: "Peñarronda",
    region: "Asturias",
    zone: "asturias",
    facing: 350,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.553,
    lon: -6.997,
    url: "https://marea.onrender.com/#/spot/penarronda",
    score: 2.4,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "5 s",
    waveDir: "NNE",
    windSpeed: "1 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,6 m",
    port: "Ribadeo",
    webcam: null,
  },
  {
    id: "frejulfe",
    name: "Frejulfe",
    region: "Asturias",
    zone: "asturias",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.56,
    lon: -6.677,
    url: "https://marea.onrender.com/#/spot/frejulfe",
    score: 2.4,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,6 m",
    wavePeriod: "5 s",
    waveDir: "NNE",
    windSpeed: "3 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,3 m",
    port: "Navia",
    webcam: null,
  },
  {
    id: "otur",
    name: "Otur",
    region: "Asturias",
    zone: "asturias",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.553,
    lon: -6.597,
    url: "https://marea.onrender.com/#/spot/otur",
    score: 2.4,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,6 m",
    wavePeriod: "6 s",
    waveDir: "N",
    windSpeed: "3 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,3 m",
    port: "Navia",
    webcam: null,
  },
  {
    id: "quebrantos",
    name: "Los Quebrantos",
    region: "Asturias",
    zone: "asturias",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.565,
    lon: -6.069,
    url: "https://marea.onrender.com/#/spot/quebrantos",
    score: 2.1,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "7 s",
    waveDir: "NNO",
    windSpeed: "7 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,7 m",
    port: "Cudillero",
    webcam: null,
  },
  {
    id: "verdicio",
    name: "Verdicio",
    region: "Asturias",
    zone: "asturias",
    facing: 330,
    facingCardinal: "NNO",
    tidePref: "Media marea",
    lat: 43.626,
    lon: -5.877,
    url: "https://marea.onrender.com/#/spot/verdicio",
    score: 3.2,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "7 s",
    waveDir: "NNO",
    windSpeed: "3 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Avilés (San Juan de Nieva)",
    webcam: null,
  },
  {
    id: "sanlorenzo",
    name: "San Lorenzo",
    region: "Asturias",
    zone: "asturias",
    facing: 20,
    facingCardinal: "NNE",
    tidePref: "Media marea",
    lat: 43.543,
    lon: -5.653,
    url: "https://marea.onrender.com/#/spot/sanlorenzo",
    score: 3.3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "6 s",
    waveDir: "NNO",
    windSpeed: "11 kn",
    windLabel: "Terral",
    windTag: "tag-terral",
    tideState: "Bajando 2,8 m",
    port: "Gijón",
    webcam: null,
  },
  {
    id: "espana",
    name: "Playa de España",
    region: "Asturias",
    zone: "asturias",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.546,
    lon: -5.529,
    url: "https://marea.onrender.com/#/spot/espana",
    score: 3.3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "6 s",
    waveDir: "NNO",
    windSpeed: "12 kn",
    windLabel: "Terral",
    windTag: "tag-terral",
    tideState: "Bajando 2,8 m",
    port: "Gijón",
    webcam: null,
  },
  {
    id: "vega",
    name: "Vega",
    region: "Asturias",
    zone: "asturias",
    facing: 10,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.48,
    lon: -5.142,
    url: "https://marea.onrender.com/#/spot/vega",
    score: 2,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,2 m",
    wavePeriod: "7 s",
    waveDir: "NNO",
    windSpeed: "8 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,5 m",
    port: "Ribadesella",
    webcam: null,
  },
  {
    id: "santamarina",
    name: "Santa Marina",
    region: "Asturias",
    zone: "asturias",
    facing: 30,
    facingCardinal: "NNE",
    tidePref: "Bajamar",
    lat: 43.467,
    lon: -5.069,
    url: "https://marea.onrender.com/#/spot/santamarina",
    score: 2.3,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,2 m",
    wavePeriod: "7 s",
    waveDir: "NNO",
    windSpeed: "3 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,5 m",
    port: "Ribadesella",
    webcam: null,
  },
  {
    id: "sanantolin",
    name: "San Antolín",
    region: "Asturias",
    zone: "asturias",
    facing: 20,
    facingCardinal: "NNE",
    tidePref: "Media marea",
    lat: 43.443,
    lon: -4.87,
    url: "https://marea.onrender.com/#/spot/sanantolin",
    score: 1,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,2 m",
    wavePeriod: "8 s",
    waveDir: "NNO",
    windSpeed: "10 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,8 m",
    port: "Llanes",
    webcam: null,
  },
  {
    id: "locos",
    name: "Los Locos",
    region: "Cantabria",
    zone: "cantabrico",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.439,
    lon: -4.048,
    url: "https://marea.onrender.com/#/spot/locos",
    score: 2.5,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,3 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "10 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Santander",
    webcam: null,
  },
  {
    id: "liencres",
    name: "Liencres",
    region: "Cantabria",
    zone: "cantabrico",
    facing: 330,
    facingCardinal: "NNO",
    tidePref: "Todas las mareas",
    lat: 43.445,
    lon: -3.971,
    url: "https://marea.onrender.com/#/spot/liencres",
    score: 2.6,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,3 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "7 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Santander",
    webcam: null,
  },
  {
    id: "somo",
    name: "Somo",
    region: "Cantabria",
    zone: "cantabrico",
    facing: 345,
    facingCardinal: "NNO",
    tidePref: "Bajamar",
    lat: 43.459,
    lon: -3.736,
    url: "https://marea.onrender.com/#/spot/somo",
    score: 3.7,
    rating: "good",
    ratingText: "Bueno",
    waveHeight: "1,1 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "3 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Santander",
    webcam: "https://playasdecantabria.es/camara-de-playa/playa-de-somo/",
  },
  {
    id: "berria",
    name: "Berria",
    region: "Cantabria",
    zone: "cantabrico",
    facing: 350,
    facingCardinal: "N",
    tidePref: "Todas las mareas",
    lat: 43.465,
    lon: -3.465,
    url: "https://marea.onrender.com/#/spot/berria",
    score: 2.7,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,0 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "6 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Santander",
    webcam: null,
  },
  {
    id: "meron",
    name: "Merón",
    region: "Cantabria",
    zone: "cantabrico",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.395,
    lon: -4.368,
    url: "https://marea.onrender.com/#/spot/meron",
    score: 2.5,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,1 m",
    wavePeriod: "8 s",
    waveDir: "NO",
    windSpeed: "9 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,8 m",
    port: "Llanes",
    webcam: null,
  },
  {
    id: "oyambre",
    name: "Oyambre",
    region: "Cantabria",
    zone: "cantabrico",
    facing: 30,
    facingCardinal: "NNE",
    tidePref: "Media marea",
    lat: 43.394,
    lon: -4.33,
    url: "https://marea.onrender.com/#/spot/oyambre",
    score: 1.2,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,1 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "9 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 2,8 m",
    port: "Llanes",
    webcam: null,
  },
  {
    id: "sardinero",
    name: "El Sardinero",
    region: "Cantabria",
    zone: "cantabrico",
    facing: 60,
    facingCardinal: "ENE",
    tidePref: "Media marea",
    lat: 43.477,
    lon: -3.786,
    url: "https://marea.onrender.com/#/spot/sardinero",
    score: 2,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,1 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Santander",
    webcam: null,
  },
  {
    id: "langre",
    name: "Langre",
    region: "Cantabria",
    zone: "cantabrico",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.476,
    lon: -3.69,
    url: "https://marea.onrender.com/#/spot/langre",
    score: 3.8,
    rating: "good",
    ratingText: "Bueno",
    waveHeight: "1,1 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Santander",
    webcam: null,
  },
  {
    id: "trengandin",
    name: "Trengandín",
    region: "Cantabria",
    zone: "cantabrico",
    facing: 20,
    facingCardinal: "NNE",
    tidePref: "Media marea",
    lat: 43.478,
    lon: -3.511,
    url: "https://marea.onrender.com/#/spot/trengandin",
    score: 3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "1,0 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Santander",
    webcam: null,
  },
  {
    id: "orinon",
    name: "Oriñón",
    region: "Cantabria",
    zone: "cantabrico",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.401,
    lon: -3.322,
    url: "https://marea.onrender.com/#/spot/orinon",
    score: 3.8,
    rating: "good",
    ratingText: "Bueno",
    waveHeight: "1,0 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "1 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Bilbao",
    webcam: null,
  },
  {
    id: "sopelana",
    name: "Sopelana",
    region: "Bizkaia",
    zone: "euskadi",
    facing: 315,
    facingCardinal: "NO",
    tidePref: "Media marea",
    lat: 43.39,
    lon: -2.993,
    url: "https://marea.onrender.com/#/spot/sopelana",
    score: 3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "1,0 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Bilbao",
    webcam: null,
  },
  {
    id: "bakio",
    name: "Bakio",
    region: "Bizkaia",
    zone: "euskadi",
    facing: 340,
    facingCardinal: "NNO",
    tidePref: "Media marea",
    lat: 43.431,
    lon: -2.806,
    url: "https://marea.onrender.com/#/spot/bakio",
    score: 3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "0,9 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "2 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,7 m",
    port: "Bermeo",
    webcam: null,
  },
  {
    id: "mundaka",
    name: "Mundaka",
    region: "Bizkaia",
    zone: "euskadi",
    facing: 330,
    facingCardinal: "NNO",
    tidePref: "Bajamar",
    lat: 43.408,
    lon: -2.694,
    url: "https://marea.onrender.com/#/spot/mundaka",
    score: 3.7,
    rating: "good",
    ratingText: "Bueno",
    waveHeight: "1,1 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "1 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,7 m",
    port: "Bermeo",
    webcam: null,
  },
  {
    id: "laarena",
    name: "La Arena",
    region: "Bizkaia",
    zone: "euskadi",
    facing: 320,
    facingCardinal: "NO",
    tidePref: "Media marea",
    lat: 43.349,
    lon: -3.117,
    url: "https://marea.onrender.com/#/spot/laarena",
    score: 3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "0,9 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "3 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Bilbao",
    webcam: null,
  },
  {
    id: "azkorri",
    name: "Azkorri",
    region: "Bizkaia",
    zone: "euskadi",
    facing: 315,
    facingCardinal: "NO",
    tidePref: "Media marea",
    lat: 43.38,
    lon: -3.017,
    url: "https://marea.onrender.com/#/spot/azkorri",
    score: 3.1,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "0,9 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "5 kn",
    windLabel: "Terral",
    windTag: "tag-terral",
    tideState: "Bajando 2,9 m",
    port: "Bilbao",
    webcam: null,
  },
  {
    id: "menakoz",
    name: "Meñakoz",
    region: "Bizkaia",
    zone: "euskadi",
    facing: 330,
    facingCardinal: "NNO",
    tidePref: "Bajamar",
    lat: 43.395,
    lon: -2.986,
    url: "https://marea.onrender.com/#/spot/menakoz",
    score: 2.9,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,0 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Bilbao",
    webcam: null,
  },
  {
    id: "laga",
    name: "Laga",
    region: "Bizkaia",
    zone: "euskadi",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.409,
    lon: -2.657,
    url: "https://marea.onrender.com/#/spot/laga",
    score: 2.8,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,0 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "6 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,7 m",
    port: "Bermeo",
    webcam: null,
  },
  {
    id: "lekeitio",
    name: "Karraspio (Lekeitio)",
    region: "Bizkaia",
    zone: "euskadi",
    facing: 25,
    facingCardinal: "NNE",
    tidePref: "Media marea",
    lat: 43.363,
    lon: -2.494,
    url: "https://marea.onrender.com/#/spot/lekeitio",
    score: 2.1,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "0,9 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "5 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 2,7 m",
    port: "Bermeo",
    webcam: null,
  },
  {
    id: "zarautz",
    name: "Zarautz",
    region: "Gipuzkoa",
    zone: "euskadi",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Todas las mareas",
    lat: 43.289,
    lon: -2.166,
    url: "https://marea.onrender.com/#/spot/zarautz",
    score: 2.9,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "0,8 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Pasajes",
    webcam: null,
  },
  {
    id: "zurriola",
    name: "La Zurriola",
    region: "Gipuzkoa",
    zone: "euskadi",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.327,
    lon: -1.976,
    url: "https://marea.onrender.com/#/spot/zurriola",
    score: 3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "0,9 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Pasajes",
    webcam: null,
  },
  {
    id: "deba",
    name: "Deba",
    region: "Gipuzkoa",
    zone: "euskadi",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 43.298,
    lon: -2.353,
    url: "https://marea.onrender.com/#/spot/deba",
    score: 3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "0,8 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,7 m",
    port: "Bermeo",
    webcam: null,
  },
  {
    id: "zumaia",
    name: "Itzurun (Zumaia)",
    region: "Gipuzkoa",
    zone: "euskadi",
    facing: 340,
    facingCardinal: "NNO",
    tidePref: "Media marea",
    lat: 43.3,
    lon: -2.261,
    url: "https://marea.onrender.com/#/spot/zumaia",
    score: 3,
    rating: "good",
    ratingText: "Aceptable",
    waveHeight: "0,8 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Pasajes",
    webcam: null,
  },
  {
    id: "orio",
    name: "Antilla (Orio)",
    region: "Gipuzkoa",
    zone: "euskadi",
    facing: 35,
    facingCardinal: "NE",
    tidePref: "Media marea",
    lat: 43.289,
    lon: -2.128,
    url: "https://marea.onrender.com/#/spot/orio",
    score: 1.7,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "0,9 m",
    wavePeriod: "9 s",
    waveDir: "NO",
    windSpeed: "5 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 2,9 m",
    port: "Pasajes",
    webcam: null,
  },
  {
    id: "matalascanas",
    name: "Matalascañas",
    region: "Huelva",
    zone: "sur",
    facing: 220,
    facingCardinal: "SO",
    tidePref: "Media marea",
    lat: 36.991,
    lon: -6.544,
    url: "https://marea.onrender.com/#/spot/matalascanas",
    score: 0,
    rating: "flat",
    ratingText: "Plato",
    waveHeight: "0,4 m",
    wavePeriod: "3 s",
    waveDir: "SSE",
    windSpeed: "2 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 1,6 m",
    port: "Bonanza (Sanlúcar de Barrameda)",
    webcam: null,
  },
  {
    id: "conil",
    name: "Fuente del Gallo",
    region: "Cádiz",
    zone: "sur",
    facing: 250,
    facingCardinal: "OSO",
    tidePref: "Media marea",
    lat: 36.29,
    lon: -6.11,
    url: "https://marea.onrender.com/#/spot/conil",
    score: 0,
    rating: "flat",
    ratingText: "Plato",
    waveHeight: "0,8 m",
    wavePeriod: "5 s",
    waveDir: "SSE",
    windSpeed: "14 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,6 m",
    port: "Conil",
    webcam: null,
  },
  {
    id: "palmar",
    name: "El Palmar",
    region: "Cádiz",
    zone: "sur",
    facing: 225,
    facingCardinal: "SO",
    tidePref: "Media marea",
    lat: 36.225,
    lon: -6.066,
    url: "https://marea.onrender.com/#/spot/palmar",
    score: 0,
    rating: "flat",
    ratingText: "Plato",
    waveHeight: "0,8 m",
    wavePeriod: "5 s",
    waveDir: "SE",
    windSpeed: "13 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,6 m",
    port: "Conil",
    webcam: null,
  },
  {
    id: "canos",
    name: "Los Caños de Meca",
    region: "Cádiz",
    zone: "sur",
    facing: 220,
    facingCardinal: "SO",
    tidePref: "Media marea",
    lat: 36.185,
    lon: -6.018,
    url: "https://marea.onrender.com/#/spot/canos",
    score: 0,
    rating: "flat",
    ratingText: "Plato",
    waveHeight: "0,9 m",
    wavePeriod: "5 s",
    waveDir: "ESE",
    windSpeed: "13 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,4 m",
    port: "Barbate",
    webcam: null,
  },
  {
    id: "costaballena",
    name: "Costa Ballena",
    region: "Cádiz",
    zone: "sur",
    facing: 260,
    facingCardinal: "O",
    tidePref: "Media marea",
    lat: 36.681,
    lon: -6.416,
    url: "https://marea.onrender.com/#/spot/costaballena",
    score: 0,
    rating: "flat",
    ratingText: "Plato",
    waveHeight: "0,5 m",
    wavePeriod: "3 s",
    waveDir: "SSE",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 2,0 m",
    port: "Chipiona",
    webcam: null,
  },
  {
    id: "santamariamar",
    name: "Santa María del Mar",
    region: "Cádiz",
    zone: "sur",
    facing: 250,
    facingCardinal: "OSO",
    tidePref: "Media marea",
    lat: 36.52,
    lon: -6.287,
    url: "https://marea.onrender.com/#/spot/santamariamar",
    score: 0.2,
    rating: "flat",
    ratingText: "Plato",
    waveHeight: "0,6 m",
    wavePeriod: "5 s",
    waveDir: "SO",
    windSpeed: "10 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,9 m",
    port: "Cádiz",
    webcam: null,
  },
  {
    id: "barrosa",
    name: "La Barrosa",
    region: "Cádiz",
    zone: "sur",
    facing: 250,
    facingCardinal: "OSO",
    tidePref: "Media marea",
    lat: 36.343,
    lon: -6.173,
    url: "https://marea.onrender.com/#/spot/barrosa",
    score: 0,
    rating: "flat",
    ratingText: "Plato",
    waveHeight: "0,8 m",
    wavePeriod: "5 s",
    waveDir: "SSE",
    windSpeed: "14 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,6 m",
    port: "Conil",
    webcam: null,
  },
  {
    id: "lances",
    name: "Los Lances (Tarifa)",
    region: "Cádiz",
    zone: "sur",
    facing: 225,
    facingCardinal: "SO",
    tidePref: "Todas las mareas",
    lat: 36.03,
    lon: -5.63,
    url: "https://marea.onrender.com/#/spot/lances",
    score: 1.4,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "0,8 m",
    wavePeriod: "7 s",
    waveDir: "ONO",
    windSpeed: "10 kn",
    windLabel: "Terral",
    windTag: "tag-terral",
    tideState: "Bajando 0,9 m",
    port: "Tarifa",
    webcam: null,
  },
  {
    id: "saler",
    name: "El Saler",
    region: "Valencia",
    zone: "mediterraneo",
    facing: 90,
    facingCardinal: "E",
    tidePref: "Todas las mareas",
    lat: 39.383,
    lon: -0.324,
    url: "https://marea.onrender.com/#/spot/saler",
    score: 0.5,
    rating: "flat",
    ratingText: "Poco oleaje",
    waveHeight: "0,5 m",
    wavePeriod: "5 s",
    waveDir: "E",
    windSpeed: "1 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Subiendo -0,4 m",
    port: "Valencia",
    webcam: null,
  },
  {
    id: "cullera",
    name: "Cullera",
    region: "Valencia",
    zone: "mediterraneo",
    facing: 100,
    facingCardinal: "E",
    tidePref: "Todas las mareas",
    lat: 39.183,
    lon: -0.219,
    url: "https://marea.onrender.com/#/spot/cullera",
    score: 0.5,
    rating: "flat",
    ratingText: "Poco oleaje",
    waveHeight: "0,5 m",
    wavePeriod: "5 s",
    waveDir: "E",
    windSpeed: "3 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Subiendo -0,4 m",
    port: "Valencia",
    webcam: null,
  },
  {
    id: "barceloneta",
    name: "Barceloneta",
    region: "Barcelona",
    zone: "mediterraneo",
    facing: 130,
    facingCardinal: "SE",
    tidePref: "Todas las mareas",
    lat: 41.379,
    lon: 2.193,
    url: "https://marea.onrender.com/#/spot/barceloneta",
    score: 2.3,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,1 m",
    wavePeriod: "5 s",
    waveDir: "ESE",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Subiendo -0,5 m",
    port: "Barcelona",
    webcam: null,
  },
  {
    id: "castelldefels",
    name: "Castelldefels",
    region: "Barcelona",
    zone: "mediterraneo",
    facing: 170,
    facingCardinal: "S",
    tidePref: "Todas las mareas",
    lat: 41.262,
    lon: 1.966,
    url: "https://marea.onrender.com/#/spot/castelldefels",
    score: 1.5,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,1 m",
    wavePeriod: "5 s",
    waveDir: "ESE",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Subiendo -0,4 m",
    port: "Barcelona",
    webcam: null,
  },
  {
    id: "pals",
    name: "Pals",
    region: "Girona",
    zone: "mediterraneo",
    facing: 90,
    facingCardinal: "E",
    tidePref: "Todas las mareas",
    lat: 41.993,
    lon: 3.202,
    url: "https://marea.onrender.com/#/spot/pals",
    score: 0.2,
    rating: "flat",
    ratingText: "Plato",
    waveHeight: "1,2 m",
    wavePeriod: "5 s",
    waveDir: "SE",
    windSpeed: "9 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Subiendo -0,5 m",
    port: "Girona",
    webcam: null,
  },
  {
    id: "mesquida",
    name: "Cala Mesquida",
    region: "Mallorca",
    zone: "mediterraneo",
    facing: 30,
    facingCardinal: "NNE",
    tidePref: "Todas las mareas",
    lat: 39.744,
    lon: 3.434,
    url: "https://marea.onrender.com/#/spot/mesquida",
    score: 1.5,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,0 m",
    wavePeriod: "5 s",
    waveDir: "ESE",
    windSpeed: "4 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Subiendo -0,4 m",
    port: "Mallorca",
    webcam: null,
  },
  {
    id: "sonbou",
    name: "Son Bou",
    region: "Menorca",
    zone: "mediterraneo",
    facing: 190,
    facingCardinal: "S",
    tidePref: "Todas las mareas",
    lat: 39.899,
    lon: 4.072,
    url: "https://marea.onrender.com/#/spot/sonbou",
    score: 0,
    rating: "flat",
    ratingText: "Plato",
    waveHeight: "1,3 m",
    wavePeriod: "5 s",
    waveDir: "ESE",
    windSpeed: "10 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Subiendo -0,4 m",
    port: "Menorca",
    webcam: null,
  },
  {
    id: "famara",
    name: "Famara",
    region: "Lanzarote",
    zone: "canarias",
    facing: 315,
    facingCardinal: "NO",
    tidePref: "Media marea",
    lat: 29.117,
    lon: -13.554,
    url: "https://marea.onrender.com/#/spot/famara",
    score: 2.6,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,7 m",
    wavePeriod: "9 s",
    waveDir: "N",
    windSpeed: "8 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,4 m",
    port: "Arrecife (Lanzarote)",
    webcam: null,
  },
  {
    id: "quemao",
    name: "El Quemao",
    region: "Lanzarote",
    zone: "canarias",
    facing: 350,
    facingCardinal: "N",
    tidePref: "Pleamar",
    lat: 29.115,
    lon: -13.651,
    url: "https://marea.onrender.com/#/spot/quemao",
    score: 1.3,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,7 m",
    wavePeriod: "9 s",
    waveDir: "N",
    windSpeed: "9 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 1,4 m",
    port: "Arrecife (Lanzarote)",
    webcam: null,
  },
  {
    id: "caballo",
    name: "Caleta de Caballo",
    region: "Lanzarote",
    zone: "canarias",
    facing: 340,
    facingCardinal: "NNO",
    tidePref: "Media marea",
    lat: 29.117,
    lon: -13.64,
    url: "https://marea.onrender.com/#/spot/caballo",
    score: 2,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,7 m",
    wavePeriod: "9 s",
    waveDir: "N",
    windSpeed: "9 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 1,4 m",
    port: "Arrecife (Lanzarote)",
    webcam: null,
  },
  {
    id: "majanicho",
    name: "Majanicho",
    region: "Fuerteventura",
    zone: "canarias",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 28.739,
    lon: -13.937,
    url: "https://marea.onrender.com/#/spot/majanicho",
    score: 1.7,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,7 m",
    wavePeriod: "9 s",
    waveDir: "N",
    windSpeed: "11 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 1,3 m",
    port: "Puerto del Rosario (Fuerteventura)",
    webcam: null,
  },
  {
    id: "rockypoint",
    name: "Rocky Point (Corralejo)",
    region: "Fuerteventura",
    zone: "canarias",
    facing: 20,
    facingCardinal: "NNE",
    tidePref: "Media marea",
    lat: 28.75,
    lon: -13.88,
    url: "https://marea.onrender.com/#/spot/rockypoint",
    score: 2.5,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,6 m",
    wavePeriod: "9 s",
    waveDir: "NNO",
    windSpeed: "5 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 1,3 m",
    port: "Puerto del Rosario (Fuerteventura)",
    webcam: null,
  },
  {
    id: "cotillo",
    name: "El Cotillo",
    region: "Fuerteventura",
    zone: "canarias",
    facing: 280,
    facingCardinal: "O",
    tidePref: "Media marea",
    lat: 28.673,
    lon: -14.01,
    url: "https://marea.onrender.com/#/spot/cotillo",
    score: 2.4,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,7 m",
    wavePeriod: "9 s",
    waveDir: "N",
    windSpeed: "11 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,3 m",
    port: "Puerto del Rosario (Fuerteventura)",
    webcam: null,
  },
  {
    id: "lapared",
    name: "La Pared",
    region: "Fuerteventura",
    zone: "canarias",
    facing: 300,
    facingCardinal: "ONO",
    tidePref: "Media marea",
    lat: 28.218,
    lon: -14.221,
    url: "https://marea.onrender.com/#/spot/lapared",
    score: 2.7,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,7 m",
    wavePeriod: "9 s",
    waveDir: "N",
    windSpeed: "7 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,1 m",
    port: "Morro Jable (Fuerteventura)",
    webcam: null,
  },
  {
    id: "confital",
    name: "El Confital",
    region: "Gran Canaria",
    zone: "canarias",
    facing: 330,
    facingCardinal: "NNO",
    tidePref: "Pleamar",
    lat: 28.158,
    lon: -15.436,
    url: "https://marea.onrender.com/#/spot/confital",
    score: 1.8,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,6 m",
    wavePeriod: "8 s",
    waveDir: "N",
    windSpeed: "6 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 1,2 m",
    port: "Puerto de la Luz (Gran Canaria)",
    webcam: null,
  },
  {
    id: "cicer",
    name: "La Cícer",
    region: "Gran Canaria",
    zone: "canarias",
    facing: 290,
    facingCardinal: "ONO",
    tidePref: "Media marea",
    lat: 28.128,
    lon: -15.448,
    url: "https://marea.onrender.com/#/spot/cicer",
    score: 2.8,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,6 m",
    wavePeriod: "8 s",
    waveDir: "N",
    windSpeed: "6 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,2 m",
    port: "Puerto de la Luz (Gran Canaria)",
    webcam: null,
  },
  {
    id: "bocabarranco",
    name: "Bocabarranco",
    region: "Gran Canaria",
    zone: "canarias",
    facing: 340,
    facingCardinal: "NNO",
    tidePref: "Media marea",
    lat: 28.159,
    lon: -15.665,
    url: "https://marea.onrender.com/#/spot/bocabarranco",
    score: 2.3,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "9 s",
    waveDir: "N",
    windSpeed: "12 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,1 m",
    port: "Puerto de las Nieves (Gran Canaria)",
    webcam: null,
  },
  {
    id: "sanfelipe",
    name: "San Felipe",
    region: "Gran Canaria",
    zone: "canarias",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 28.144,
    lon: -15.6,
    url: "https://marea.onrender.com/#/spot/sanfelipe",
    score: 1.6,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,6 m",
    wavePeriod: "8 s",
    waveDir: "N",
    windSpeed: "12 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 1,1 m",
    port: "Puerto de las Nieves (Gran Canaria)",
    webcam: null,
  },
  {
    id: "americas",
    name: "Las Américas",
    region: "Tenerife",
    zone: "canarias",
    facing: 225,
    facingCardinal: "SO",
    tidePref: "Media marea",
    lat: 28.062,
    lon: -16.734,
    url: "https://marea.onrender.com/#/spot/americas",
    score: 2,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,0 m",
    wavePeriod: "9 s",
    waveDir: "NNO",
    windSpeed: "3 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 1,0 m",
    port: "Los Cristianos (Tenerife)",
    webcam: null,
  },
  {
    id: "socorro",
    name: "El Socorro",
    region: "Tenerife",
    zone: "canarias",
    facing: 330,
    facingCardinal: "NNO",
    tidePref: "Media marea",
    lat: 28.394,
    lon: -16.603,
    url: "https://marea.onrender.com/#/spot/socorro",
    score: 2.9,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,4 m",
    wavePeriod: "8 s",
    waveDir: "N",
    windSpeed: "5 kn",
    windLabel: "Cruzado",
    windTag: "tag-neutral",
    tideState: "Bajando 1,2 m",
    port: "Puerto de la Cruz (Tenerife)",
    webcam: null,
  },
  {
    id: "martianez",
    name: "Martiánez",
    region: "Tenerife",
    zone: "canarias",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 28.418,
    lon: -16.541,
    url: "https://marea.onrender.com/#/spot/martianez",
    score: 2.6,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,5 m",
    wavePeriod: "9 s",
    waveDir: "N",
    windSpeed: "5 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 1,2 m",
    port: "Puerto de la Cruz (Tenerife)",
    webcam: null,
  },
  {
    id: "almaciga",
    name: "Almáciga",
    region: "Tenerife",
    zone: "canarias",
    facing: 0,
    facingCardinal: "N",
    tidePref: "Media marea",
    lat: 28.572,
    lon: -16.193,
    url: "https://marea.onrender.com/#/spot/almaciga",
    score: 2,
    rating: "fair",
    ratingText: "Aceptable",
    waveHeight: "1,6 m",
    wavePeriod: "9 s",
    waveDir: "N",
    windSpeed: "9 kn",
    windLabel: "De mar",
    windTag: "tag-neutral",
    tideState: "Bajando 1,2 m",
    port: "Santa Cruz de Tenerife",
    webcam: null,
  },
  {
    id: "medano",
    name: "El Médano",
    region: "Tenerife",
    zone: "canarias",
    facing: 130,
    facingCardinal: "SE",
    tidePref: "Todas las mareas",
    lat: 28.044,
    lon: -16.539,
    url: "https://marea.onrender.com/#/spot/medano",
    score: 1.5,
    rating: "poor",
    ratingText: "Poco oleaje",
    waveHeight: "1,3 m",
    wavePeriod: "5 s",
    waveDir: "NE",
    windSpeed: "3 kn",
    windLabel: "Calma",
    windTag: "tag-neutral",
    tideState: "Bajando 1,0 m",
    port: "Granadilla (Tenerife)",
    webcam: null,
  },
];
