default_platform(:ios)

platform :ios do
  desc "Ejecuta los tests unitarios de iOS"
  lane :test do
    scan(
      project: "Marea.xcodeproj",
      scheme: "Marea",
      destination: "platform=iOS Simulator,name=iPhone 17"
    )
  end

  desc "Compila la app para release"
  lane :build do
    gym(
      project: "Marea.xcodeproj",
      scheme: "Marea",
      export_method: "app-store",
      output_directory: "./build"
    )
  end

  desc "Sube una nueva versión a TestFlight"
  lane :beta do
    test
    build
    pilot(
      skip_waiting_for_build_processing: true
    )
  end
end
